//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationExperience
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class For_TestEntities : DbContext
    {
        public For_TestEntities()
            : base("name=For_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountData> AccountData { get; set; }
        public virtual DbSet<HallWithStaff> HallWithStaff { get; set; }
        public virtual DbSet<StaffData> StaffData { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestData> TestData { get; set; }
        public virtual DbSet<TravelAgencyData> TravelAgencyData { get; set; }
        public virtual DbSet<TravelAgencyUserData> TravelAgencyUserData { get; set; }
        public virtual DbSet<ExhibitionActivityWithHall> ExhibitionActivityWithHall { get; set; }
    }
}
